{
	"name": "CI",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		},
		"pull_request": {
			"branches": [
				"main"
			]
		},
		"workflow_dispatch": null
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v3"
				},
				{
					"name": "Run a multi-line script",
					"run": "echo Hello, world!,\n\necho Gaurav"
				},
				{
					"name": "Run a multi-line script",
					"run": "echo Add other actions to build,\necho test, and deploy your project.\n"
				}
			]
		}
	}
}
